### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by dengwen168** [django/django-contrib-comments#152] opened 2020-04-26 12:58 UTC
When i click the "submit" button, I got the following information:

Request Method: | POST
-- | --
http://127.0.0.1:8000/comments/post/
2.0
IndexError
list index out of range
H:\py_project\weather\weathervenv\lib\site-packages\django\db\models\query.py in __getitem__, line 307
H:\py_project\weather\weathervenv\Scripts\python.exe
3.6.5

**Comment by jhabarsingh** [comment] 2020-07-24 06:05
can i work on this issue ?

**Comment by claudep** [comment] 2020-07-24 07:00
Of course, but do you think you have enough information to find the root cause?

**Comment by jhabarsingh** [comment] 2020-07-24 14:23
yeah i feel the information is not sufficient, to work on this issue. sorry for that .

**Comment by claudep** [comment] 2020-07-24 14:28
No problem, closing for lack of reproducible information.

**Closed by claudep** 2020-07-24 14:28 UTC
